"""Add date_value column.

Revision ID: 02fe023f8b3b
Revises:
Create Date: 2024-12-14 16:45:34.641077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "02fe023f8b3b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """

    Apply the database migration to add the 'date_value' column to the 'sheet_data' table.

    This column is of type DateTime
    and allows null values.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sheet_data", sa.Column("date_value", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the database migration by removing the 'date_value' column from the 'sheet_data' table."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sheet_data", "date_value")
    # ### end Alembic commands ###
