"""Add comments column

Revision ID: 10ed662a9b4a
Revises: ea21830eccf5
Create Date: 2024-12-26 14:34:28.921019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10ed662a9b4a'
down_revision: Union[str, None] = 'ea21830eccf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sheet_data', 'comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sheet_data', sa.Column('comments', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
